networks:
  theblog-network:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theblog-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - theblog-network
